version: "3.0"
services:
  webserver:
    image: nginx:1.17-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel_network
  phpservice:
    build:
      context: docker/php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel_network
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: academia
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel_network


networks:
  laravel_network:
    driver: bridge